name: zz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  geolocator: ^14.0.2
  geocoding: ^2.0.5
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.2 
  firebase_auth: ^6.0.2
  permission_handler: ^12.0.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/jpg/
    - assets/png/   
    - assets/jpeg/

